version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - davwheat
  assignees:
  - davwheat
  labels:
  - dependencies
  - "bot: dependabot"
  ignore:
  - dependency-name: webpack
    versions:
    - 5.22.0
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.0
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: "@sentry/integrations"
    versions:
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.3.0
    - 6.3.1
  - dependency-name: react-virtuoso
    versions:
    - 1.5.0
    - 1.5.13
    - 1.5.14
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.6.0
    - 1.8.0
    - 1.8.1
    - 1.8.2
    - 1.8.4
    - 1.8.5
  - dependency-name: open
    versions:
    - 7.4.1
    - 7.4.2
    - 8.0.1
    - 8.0.2
    - 8.0.3
    - 8.0.4
    - 8.0.5
    - 8.0.6
  - dependency-name: electron
    versions:
    - 12.0.0
    - 12.0.1
    - 12.0.2
    - 12.0.4
  - dependency-name: css-loader
    versions:
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.12
    - 7.13.9
  - dependency-name: "@sentry/electron"
    versions:
    - 2.3.0
    - 2.4.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.7
    - 1.3.8
    - 1.3.9
  - dependency-name: "@babel/eslint-parser"
    versions:
    - 7.12.17
    - 7.13.0
    - 7.13.4
  - dependency-name: eslint-plugin-jsdoc
    versions:
    - 31.4.0
    - 31.6.0
    - 31.6.1
    - 32.0.0
    - 32.0.1
    - 32.0.2
    - 32.1.0
    - 32.2.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
    - 7.13.1
  - dependency-name: "@sentry/webpack-plugin"
    versions:
    - 1.14.1
  - dependency-name: core-js
    versions:
    - 3.9.0
  - dependency-name: adm-zip
    versions:
    - 0.5.3
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
  - dependency-name: dayjs
    versions:
    - 1.10.4
  - dependency-name: "@fontsource/ibm-plex-mono"
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: "@fontsource/poppins"
    versions:
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: less-loader
    versions:
    - 7.3.0
  - dependency-name: html-webpack-plugin
    versions:
    - 4.5.1
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: webpack-dev-server
    versions:
    - 3.11.2
